name: appointment-docker-build
env:
  docker_repo: appointment-service
  aws_accountid: "539935451710"
  location: us-east-1
on:
  push:
    branches:
      - main
    paths:
      - 'appointment-service/**'        

jobs:
  build:
    runs-on: ubuntu-latest   # Run the workflow on the latest Ubuntu environment

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Set the Node.js version you want to use

      # Step 3: Install dependencies
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Set up AWS OIDC
      - name: Set up AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ env.aws_accountid }}:role/<role-name>  # Replace with your IAM role ARN
          role-session-name: GitHubActions
          aws-region: ${{ env.location }}

      # Step 4: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region ${{ env.location }} | docker login --username AWS --password-stdin ${{ env.aws_accountid }}.dkr.ecr.us-east-1.amazonaws.com

      # Step 5: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ env.aws_accountid }}.dkr.ecr.${{ env.location }}.amazonaws.com/${{ env.docker_repo }}:1.0.0.${{ github.run_number }} ./appointment-service/Dockerfile
       
      # Step 6: Push the Docker image to ECR
      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ env.aws_accountid }}.dkr.ecr.${{ env.location }}.amazonaws.com/${{ env.docker_repo }}:1.0.0.${{ github.run_number }}

      - name: Clean up Docker images
        run: |
          docker system prune -af
      - name: chage build version in helm
        run: |
          cd $HOME
          sudo rm -R -f eks-hcl-task-helm          
          git clone https://${{ secrets.CICD_GIT_AUTH }}@github.com/venkat1696/eks-hcl-task-helm.git
          cd eks-hcl-task-helm
          find . -type f -exec sed -i '0,/${{ env.docker_repo }}:1.0.0.[0-9]*/ s+${{ env.docker_repo }}:1.0.0.[0-9]*+${{ env.docker_repo }}:1.0.0.${{ github.run_number }}+g' values.yaml \;
          cd ../
          git status
          git add *
          git commit -m "changing docker tag version in ${{ env.docker_repo }}"
          git push origin main